### ISSUE TITLE
Type problem when no data_to_track in minimize_states

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/BiorbdOptim#98] opened 2020-05-22 15:46 UTC
File "/home/user/Documents/Programmation/BiorbdOptim/biorbd_optim/penalty.py", line 26, in minimize_states
    val = v[states_idx] - data_to_track[t[i], states_idx]
  File "/home/user/anaconda3/envs/Trampo_biorbdOptim/lib/python3.7/site-packages/casadi/casadi.py", line 6497, in __array__
    + "Use an equivalent CasADi function instead of that numpy function.")
Exception: Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function.

**Comment by pariterre** [comment] 2020-05-23 01:17
Hi @EveCharbie !
Could you provide a failing minimal example please :)

**Comment by EveCharbie** [comment] 2020-05-25 14:53
Sorry, I looked further into it and I think the problem is 'Instant.END'

Code:
`import numpy as np
import biorbd
from IPython import embed
import casadi

from sys import path
path.append("/home/user/Documents/Programmation/BiorbdOptim")

from biorbd_optim import (
    OptimalControlProgram,
    Objective,
    ProblemType,
    BidirectionalMapping,
    Mapping,
    Bounds,
    QAndQDotBounds,
    InitialConditions,
    ShowResult,
    Instant,
)


def prepare_ocp(biorbd_model, phase_time, number_shooting_points):

    # --- Options --- #
    nb_q = biorbd_model.nbQ()
    nb_qdot = nb_q
    nb_root = 6
    nb_tau = nb_q - nb_root

    # tolerances on final position of the root
    tolTilt = 15   # Tilt angle
    tolSom = 10   # Somersault angle

    torque_min, torque_max, torque_init = -500, 500, 0

    # Add objective functions
    objective_functions = (
            # {"type": Objective.Lagrange.MINIMIZE_MARKERS_DISPLACEMENT, "rt_idx": 0, "markers_idx": 5, "weight": 1/100},
            {"type": Objective.Mayer.MINIMIZE_STATE, "instant": Instant.END, "data_to_track": 0, "states_idx": 5, "weight": -1}, # 5
            # {"type": Objective.Lagrange.MINIMIZE_ALL_CONTROLS, "weight": 1 / 100},
    )

    # Dynamics
    problem_type = ProblemType.torque_driven

    # Constraints
    constraints = ()



    # Path constraints
    pose_at_first_node = [0, 0, 0, 0, 0, 0, -2.8, 2.8]

    QinitMin = [-0.0001, -0.0001, -0.0001, -0.0001, -0.0001, -0.0001, -2.8-0.0001, 2.8-0.0001]
    QinitMax = [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, -2.8+0.0001, 2.8+0.0001]
    VinitMin = [-10, -10, -10, -100, -0.0001, -0.0001, -0.0001, -0.0001]
    VinitMax = [10, 10, 10, 100, 0.0001, 0.0001, 0.0001, 0.0001]

    Qmin = [-1000000, -1000000, -1000000, -1000000, -np.pi/4, -1000000, -np.pi, 0]
    Qmax = [1000000,  1000000, 1000000,   1000000,  np.pi/4,  1000000,  0,   np.pi]
    Vmin = [-1000000, -1000000,  -1000000,  -1000000,  -1000000, -1000000, -100, -100]
    Vmax = [1000000,  1000000,   1000000,   1000000,   1000000,  1000000,  100,  100]

    QfinalMin = [-1, -1, -0.1, 2*np.pi-tolSom*np.pi/180, -tolTilt/180*np.pi, -1000000, -2.9, 2.7]
    QfinalMax = [1,  1, 0.1,   2*np.pi+tolSom*np.pi/180,  tolTilt/180*np.pi,  1000000, -2.7, 2.9]
    VfinalMin = [-1000000, -1000000,  -1000000,  -1000000,  -1000000, -1000000, -100, -100]
    VfinalMax = [1000000,  1000000,   1000000,   1000000,   1000000,  1000000,  100,  100]

    # Initialize X_bounds
    X_bounds = QAndQDotBounds(biorbd_model)
    X_bounds.min[:, 0] = QinitMin + VinitMin
    X_bounds.max[:, 0] = QinitMax + VinitMax

    X_bounds.min[:, 1] = Qmin + Vmin
    X_bounds.max[:, 1] = Qmax + Vmax

    X_bounds.min[:, -1] = QfinalMin + VfinalMin
    X_bounds.max[:, -1] = QfinalMax + VfinalMax

    # Initial guess
    X_init = InitialConditions(pose_at_first_node + [0] * nb_qdot)

    # Define control path constraint
    U_bounds = Bounds(min_bound=[torque_min] * nb_q, max_bound=[torque_max] * nb_q)

    U_init = InitialConditions([torque_init] * nb_q)

    # ------------- #
    return OptimalControlProgram(
        biorbd_model,
        problem_type,
        number_shooting_points,
        phase_time,
        X_init,
        U_init,
        X_bounds,
        U_bounds,
        objective_functions,
        constraints,
    )


if __name__ == "__main__":
    biorbd_model = biorbd.Model("/home/user/Documents/Programmation/Eve/Modeles/ModeleBatons_2D_CAS.bioMod")
    t = 1.22
    ns = 300 # number of shooting intervals
    ocp = prepare_ocp(biorbd_model=biorbd_model, phase_time=t, number_shooting_points=ns)

    # --- Solve the program --- #
    sol = ocp.solve(show_online_optim=True)

    # --- Show results --- #
    result = ShowResult(ocp, sol)
    result.animate(nb_frames=40)
`
With model :
`version	3

// General informations
root_actuated 1
external_forces 0



//__________________________________________
// Informations about Pelvis segment
	// Segment
	segment	Pelvis
		translations xyz
		rotations	xyz
		mass	58.801
		inertia
			7.85829	0.00000	0.00000
			0.00000	8.12771	0.00000
			0.00000	0.00000	0.51802
		com		0  0  0.09410
		mesh	0	0	-1
		mesh	0	0	1
		mesh	0	0	-1

	endsegment

	// Actuator
		actuator	Pelvis
			type	Constant
			dof	RotX
			direction	positive
			Tmax	0.0			
		endactuator
		actuator	Pelvis
			type	Constant
			dof	RotX
			direction	negative
			Tmax	0.0			
		endactuator
		actuator	Pelvis
			type	Constant
			dof	RotY
			direction	positive
			Tmax	0.0			
		endactuator
		actuator	Pelvis
			type	Constant
			dof	RotY
			direction	negative
			Tmax	0.0			
		endactuator
		actuator	Pelvis
			type	Constant
			dof	RotZ
			direction	positive
			Tmax	0.0			
		endactuator
		actuator	Pelvis
			type	Constant
			dof	RotZ
			direction	negative
			Tmax	0.0			
		endactuator
		actuator	Pelvis
			type	Constant
			dof	TransX
			direction	positive
			Tmax	0.000000
		endactuator
		actuator	Pelvis
			type	Constant
			dof	TransX
			direction	negative
			Tmax	0.000000
		endactuator
		actuator	Pelvis
			type	Constant
			dof	TransY
			direction	positive
			Tmax	0.000000
		endactuator
		actuator	Pelvis
			type	Constant
			dof	TransY
			direction	negative
			Tmax	0.000000
		endactuator
		actuator	Pelvis
			type	Constant
			dof	TransZ
			direction	positive
			Tmax	0.000000
		endactuator
		actuator	Pelvis
			type	Constant
			dof	TransZ
			direction	negative
			Tmax	0.000000
		endactuator
		
	// Markers
		marker	Jambes
			parent	Pelvis
			position	0	0	 -1
			technical 1
		endmarker
		marker Cou
			parent Pelvis
			position	0	0   1
		endmarker


// Informations about BrasD segment
	// Segment
	segment	BrasD
		parent	Pelvis
		RT 0 0 0 xyz 0.1875 0.0205 0.4719
		rotations	y
		mass	3.106
		inertia
			0.0910283	0.00000	    0.00000
			0.00000	    0.0909983	0.00000
			0.00000	    0.00000	    0.00292
		com		0		0		-0.233088
		mesh	0	0	-0.4662
		mesh	0	0	0
		mesh	0	0	-0.4662

	endsegment

	// Actuator
		actuator	BrasD
			type	Gauss6p
			dof	RotY
			direction	negative
			Tmax	32.655002
			T0	25.780265
			wmax	812.499995
			wc	324.999996
			amin	0.500000
			wr	28.424707
			w1	90.000000
			r	28.832873
			qopt	133.000000
			facteur	3.862687
			r2	73.500000
			qopt2	73.500000
		endactuator
		actuator	BrasD
			type	Gauss6p
			dof	RotY
			direction	positive
			Tmax	41.779398
			T0	32.853388
			wmax	1000.000000
			wc	400.000000
			amin	0.602364
			wr	10.177422
			w1	47.600548
			r	74.100000
			qopt	132.416627
			facteur	2.080254
			r2	60.375000
			qopt2	24.694161
		endactuator

	// Markers
		marker	EpauleDroite
			parent	BrasD
			position	0	0	0
			technical 1
		endmarker
		marker	PoignetDroite
			parent	BrasD
			position	0	0	-0.4662
			technical 1
		endmarker


// Informations about BrasG segment
	// Segment
	segment	BrasG
		parent	Pelvis
		RT 0 0 0 xyz -0.1875 0.0205 0.4719
		rotations	y
		mass	3.106
		inertia
			0.0910283	0.00000	    0.00000
			0.00000	    0.0909983	0.00000
			0.00000  	0.00000	    0.00292
		com		0		0		-0.233088
		mesh	0	0	-0.4662
		mesh	0	0	0
		mesh	0	0	-0.4662
		
	endsegment

	// Actuator
		actuator	BrasG
			type	Gauss6p
			dof	RotY
			direction	positive
			Tmax	32.655002
			T0	25.780265
			wmax	812.499995
			wc	324.999996
			amin	0.500000
			wr	28.424707
			w1	90.000000
			r	28.832873
			qopt	133.000000
			facteur	3.862687
			r2	73.500000
			qopt2	73.500000
		endactuator
		actuator	BrasG
			type	Gauss6p
			dof	RotY
			direction	negative
			Tmax	41.779398
			T0	32.853388
			wmax	1000.000000
			wc	400.000000
			amin	0.602364
			wr	10.177422
			w1	47.600548
			r	74.100000
			qopt	132.416627
			facteur	2.080254
			r2	60.375000
			qopt2	24.694161
		endactuator

	// Markers
		marker	EpauleGauche
			parent	BrasG
			position	0	0	0
			technical 1
		endmarker
		marker	PoignetGauche
			parent	BrasG
			position	0	0	-0.4662
			technical 1
		endmarker
`

**Comment by pariterre** [comment] 2020-06-08 20:53
This must have been fixed by chance since, because the bug can't be reproduced

**Comment by pariterre** [comment] 2020-06-08 20:54
That said, if your data_to_track are zero, then you don't have to specify them!

**Closed by pariterre** 2020-06-08 20:53 UTC
Labels: bug
